version: '3.8'

services:
  # authentication-service:
  #   build:
  #     context: ./../authentication-service
  #     dockerfile: ./../authentication-service/authentication-service.dockerfile
  #   restart: always
  #   ports:
  #     - "5052:5050"
  gateway-service:
    build:
      context: ./../gateway-service
      dockerfile: ./../gateway-service/gateway-service.dockerfile
      target: dev
    env_file:
      - ./../gateway-service/.env
    ports:
      - "3000:3000"
    volumes:
      - ./../gateway-service:/app
  listner-service:
    build:
      context: ./../listner-service
      dockerfile: ./../listner-service/listner-service.dockerfile
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - ./../listner-service/:/app
