version: '3.8'

services:
  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    environment:
      MongoUrl: mongodb://mongo-db:27017
      dbName: auth-service
      MongoUsername: root
      MongoPassword: mongo
      collectionName: example
      testHandler: asdasd
      kafkaURL: kafka:9092
      topic: twitter.newTweets
      GroupID: mongo-group
    ports:
      - "5052:5050"
    depends_on:
      - kafka
      - mongo-db
  gateway-service:
    build:
      context: ./../gateway-service
      dockerfile: ./../gateway-service/gateway-service.dockerfile
      target: dev
    environment:
      PORT: 3000
      KAFKA_TOPIC: twitter.newTweets
      KAFKA_URL: kafka:9092
    ports:
      - "4000:4000"
    volumes:
      - ./../gateway-service:/app
    depends_on:
      - kafka
  listner-service:
    build:
      context: ./../listner-service
      dockerfile: ./../listner-service/listner-service.dockerfile
      target: dev

    ports:
      - "5004:5004"
    volumes:
      - ./../listner-service/:/app
  mongo-db:
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://root:mongo@mongo-db:27017
    depends_on:
      - mongo-db
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"
    # volumes:
    #   - zookeeper:/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: wurstmeister/kafka
    restart: always

    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # volumes:
    #   - ./db-data/rabbitmq/:/var/lib/rabbitmq/





