version: '3.8'

services:
  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
      target: dev
    restart: always
    ports:
      - "5050:5050"
  gateway-service:
    build:
      context: ./../gateway-service
      dockerfile: ./../gateway-service/gateway-service.dockerfile
      target: dev
    restart: always
    ports:
      - "5051:5050"
