version: '3.8'

services:
  # authentication-service:
  #   build:
  #     context: ./../authentication-service
  #     dockerfile: ./../authentication-service/authentication-service.dockerfile
  #   restart: always
  #   ports:
  #     - "5052:5050"
  gateway-service:
    build:
      context: ./../gateway-service
      dockerfile: ./../gateway-service/gateway-service.dockerfile
      target: dev
    env_file:
      - ./../gateway-service/.env
    ports:
      - "3000:3000"
    volumes:
      - ./../gateway-service:/app
  listner-service:
    build:
      context: ./../listner-service
      dockerfile: ./../listner-service/listner-service.dockerfile
      target: dev

    ports:
      - "5000:5000"
    volumes:
      - ./../listner-service/:/app

  rabbitmq:
    image: rabbitmq:3.12.10-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_PORT: 5672
      RABBITMQ_DEFAULT_HOST: rabbitmq
    ports:
      - "5672:5672"
    # volumes:
    #   - ./db-data/rabbitmq/:/var/lib/rabbitmq/
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
  rabbitmq-management:
    image: rabbitmq:3.12.10-management-alpine
    restart: always
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_HOST: rabbitmq
    ports:
      - "15672:15672"
