version: '3.8'

services:
  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    environment:
      MongoUrl: mongodb://mongo-db:27017
      dbName: auth-service
      MongoUsername: root
      MongoPassword: mongo
      collectionName: example
      kafkaURL: kafka:9092
      topic: my-topic
    ports:
      - "5052:5050"
    depends_on:
      - kafka
      - mongo-db
  gateway-service:
    build:
      context: ./../gateway-service
      dockerfile: ./../gateway-service/gateway-service.dockerfile
      target: dev
    env_file:
      - ./../gateway-service/.env
    ports:
      - "3000:3000"
    volumes:
      - ./../gateway-service:/app
    depends_on:
      - kafka
  listner-service:
    build:
      context: ./../listner-service
      dockerfile: ./../listner-service/listner-service.dockerfile
      target: dev

    ports:
      - "5000:5000"
    volumes:
      - ./../listner-service/:/app
  mongo-db:
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://root:mongo@mongo-db:27017
    depends_on:
      - mongo-db
  zookeeper:
    image: bitnami/zookeeper:3.9
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    restart: always
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9092:9092"
      - "9094:9094"
      - "9093:9093"
    depends_on:
      - zookeeper
    # volumes:
    #   - ./db-data/rabbitmq/:/var/lib/rabbitmq/
    volumes:
      - kafka_data:/bitnami

volumes:
  kafka_data:
  zookeeper-data:


